# Generated by Django 4.0.6 on 2023-02-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('leavetracker', '0002_alter_leaverequest_request_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestleaverequestnumber',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', unique=True),
        ),
    ]
