# Generated by Django 4.0.6 on 2023-02-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('leavetracker', '0003_alter_latestleaverequestnumber_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestleaverequestnumber',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
