# Generated by Django 4.0.6 on 2023-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0004_alter_latestleaverequestnumber_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
