# Generated by Django 4.0.6 on 2023-02-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0005_alter_access_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='access',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
