# Generated by Django 4.0.6 on 2023-02-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectadminrole_name'),
        ('leavetracker', '0006_alter_access_unique_together_alter_access_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'project')},
        ),
    ]
