# Generated by Django 4.0.6 on 2023-03-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0007_alter_team_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavetracker.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_team', to='leavetracker.announcement')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_team', to='leavetracker.team')),
            ],
        ),
    ]
