# Generated by Django 4.0.6 on 2023-03-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0010_alter_announcement_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementViewedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_viewed_by', to='leavetracker.announcement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_viewed_by', to='leavetracker.employee')),
            ],
        ),
    ]
