# Generated by Django 4.0.6 on 2023-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0012_alter_announcementviewedemployee_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
