# Generated by Django 4.0.6 on 2023-03-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavetracker', '0013_announcement_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_team', to='leavetracker.team'),
        ),
    ]
