# Generated by Django 4.0.6 on 2023-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectadminaccess_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectadminrole',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
